services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CORS_ORIGINS_STR=${CORS_ORIGINS_STR}
      - HOST=0.0.0.0
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot-network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_URL=http://api:8000
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
